name: CI
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
